=head1 NAME

qps

=head1 SYNOPSIS

B<qps> [B<-h>] [B<-s> server] [B<-o> B<indent>|B<xml>|B<json>|B<perl>|B<qstat>] [B<-a> attr1,attr2] [B<-f> attr3=foo] [jobid1 jobid2 ...]

=head1 DESCRIPTION

A "better" qstat.

=head1 OPTIONS

=over

=item B<-h>

Show help

=item B<-s>

Torque server to connect to

=item B<-o> B<indent>|B<xml>|B<json>|B<perl>|B<qstat>

Select the output format, the default is B<indent>.

=item B<-a> attr1,attr2

Comma seperated list of attributes to display. C<all> indicates that all of the attributes returned by the server should be shown.

=item B<-f> attr=FOO

Filter output on the basis of attribute values. Comma seperated list. The comparison operators are:

=over

=item =

Equality, e.g.:

  Job_Name=STDIN

=item !=

Inequality, e.g.

  Job_Name!=STDIN

=back

Remaining arguments are treated as job ID, and only those IDs provided will be shown (after filtering is applied).

=back

=head1 EXAMPLES

Show jobs called STDIN and their owner:

  qps -a Job_Owner -f Job_Name=STDIN

Show the Job_Owner of jobs called STDIN from jobs 1, 2, and 3:

  qps -a Job_Owner -f Job_Name=STDIN 1 2 3

=head1 SEE ALSO

L<qstat(1B)>

=head1 AUTHOR

Jonathan Barber - <jonathan.barber@gmail.com>

=cut
